version: '3'
services:
  app:
    image: flask_app:latest
    container_name: flask_app
    restart: unless-stopped
    labels:
      project: "flask"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      DB_NAME: flask
      DB_USER: flask
      DB_PASSWORD: slimdingo85
    links:
      - mysql
    depends_on:
     - mysql
    ports:
      - "5000:5000"

  mysql:
    container_name: flask_mysql
    image: mysql:5.7
    volumes:
      - mysql-data1:/var/lib/mysql
    restart: unless-stopped
    labels:
      project: "flask"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: slimdingo85
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: slimdingo85
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    container_name: flask_phpmyadmin
    restart: unless-stopped
    labels:
      project: "flask"
    ports:
      - "5010:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: flask
      PMA_PASSWORD: slimdingo85
      MYSQL_ROOT_PASSWORD: slimdingo85

volumes:
  mysql-data1:
    driver: local
